// Central config describing every module/route in the app and which roles can access it.
// This mirrors the "Role-Based Access Summary" from the product design + the detailed
// per-role UI/UX specs (Member, Chairman, Secretary, Accountant, Treasurer, Security Staff,
// Committee Member, Tenant, Housekeeping Staff).
import {
  LayoutDashboard,
  Users,
  Building2,
  Wallet,
  UserCheck,
  MessageSquareWarning,
  Wrench,
  Megaphone,
  Dumbbell,
  FileText,
  BarChart3,
  Settings,
  ShieldAlert,
  Video,
  ScrollText,
  TrendingUp,
  PiggyBank,
  CalendarDays,
  Vote,
  Receipt,
  KeyRound,
  Clock4,
  ClipboardList,
  Boxes,
  FileSignature,
} from 'lucide-react';

export const ALL_ROLES = [
  'admin',
  'security',
  'resident',
  'accountant',
  'secretary',
  'chairman',
  'treasurer',
  'committee_member',
  'tenant',
  'housekeeping',
];

export const NAV_ITEMS = [
  { name: 'Dashboard', path: '/', icon: LayoutDashboard, roles: ALL_ROLES },

  // Owner/tenant self-service
  { name: 'My Dues', path: '/my-dues', icon: Receipt, roles: ['resident', 'tenant'] },

  { name: 'Residents', path: '/residents', icon: Users, roles: ['admin', 'security', 'secretary', 'chairman', 'treasurer', 'committee_member'] },
  { name: 'Gate Passes', path: '/gate-passes', icon: KeyRound, roles: ['admin', 'security', 'secretary', 'chairman', 'resident', 'tenant'] },
  { name: 'Staff Shifts', path: '/shifts', icon: Clock4, roles: ['admin', 'security', 'secretary', 'chairman', 'housekeeping'] },
  { name: 'Daily Tasks', path: '/tasks', icon: ClipboardList, roles: ['admin', 'secretary', 'chairman', 'housekeeping'] },
  { name: 'Supplies', path: '/supplies', icon: Boxes, roles: ['admin', 'secretary', 'chairman', 'housekeeping'] },
  { name: 'Lease Management', path: '/leases', icon: FileSignature, roles: ['admin', 'secretary', 'chairman', 'committee_member', 'tenant'] },
  { name: 'Units / Flats', path: '/units', icon: Building2, roles: ['admin', 'secretary', 'chairman'] },
  { name: 'Finance', path: '/finance', icon: Wallet, roles: ['admin', 'accountant', 'secretary', 'chairman', 'treasurer', 'committee_member'] },
  { name: 'Visitors', path: '/visitors', icon: UserCheck, roles: ['admin', 'security', 'secretary', 'chairman', 'tenant'] },
  { name: 'Complaints', path: '/complaints', icon: MessageSquareWarning, roles: ALL_ROLES },
  { name: 'Maintenance', path: '/maintenance', icon: Wrench, roles: ALL_ROLES },
  { name: 'Notice Board', path: '/notices', icon: Megaphone, roles: ALL_ROLES },
  { name: 'Amenities', path: '/amenities', icon: Dumbbell, roles: ALL_ROLES },
  { name: 'Documents', path: '/documents', icon: FileText, roles: ['admin', 'secretary', 'chairman', 'accountant', 'treasurer', 'committee_member'] },
  { name: 'Meetings', path: '/meetings', icon: CalendarDays, roles: ALL_ROLES.filter((r) => r !== 'housekeeping') },
  { name: 'Voting / Polls', path: '/voting', icon: Vote, roles: ALL_ROLES.filter((r) => r !== 'housekeeping' && r !== 'security') },
  { name: 'Emergency (SOS)', path: '/emergency', icon: ShieldAlert, roles: ALL_ROLES },
  { name: 'Camera Requests', path: '/camera-requests', icon: Video, roles: ['admin', 'security', 'secretary', 'chairman', 'resident', 'treasurer', 'committee_member', 'tenant'] },
  { name: 'Society Policies', path: '/policies', icon: ScrollText, roles: ALL_ROLES },
  { name: 'Investments & Assets', path: '/investments', icon: TrendingUp, roles: ['admin', 'accountant', 'secretary', 'chairman', 'treasurer', 'committee_member'] },
  { name: 'Funds', path: '/funds', icon: PiggyBank, roles: ALL_ROLES.filter((r) => r !== 'housekeeping') },
  { name: 'Reports', path: '/reports', icon: BarChart3, roles: ['admin', 'accountant', 'secretary', 'chairman', 'treasurer'] },
  { name: 'Settings', path: '/settings', icon: Settings, roles: ['admin'] },
];
