// Central config describing every module/route in the app and which roles can access it.
// This mirrors the "Role-Based Access Summary" from the product design + the detailed
// per-role UI/UX specs (Member, Chairman, Secretary, Accountant, Treasurer, Security Staff,
// Committee Member, Tenant, Housekeeping Staff).
import {
  LayoutDashboard,
  Users,
  Building2,
  Wallet,
  UserCheck,
  MessageSquareWarning,
  Wrench,
  Megaphone,
  Dumbbell,
  FileText,
  BarChart3,
  Settings,
  ShieldAlert,
  Video,
  ScrollText,
  TrendingUp,
  PiggyBank,
  CalendarDays,
  Vote,
  Receipt,
  KeyRound,
  Clock4,
  ClipboardList,
  Boxes,
  FileSignature,
  PawPrint,
  CreditCard,
  Users2,
  Car,
  HomeIcon,
  ClipboardCheck,
  UserCheck2,
  ListChecks,
  Tag,
  Gavel,
  SquareParking,
} from 'lucide-react';

export const ALL_ROLES = [
  'security',
  'resident',
  'accountant',
  'secretary',
  'chairman',
  'treasurer',
  'committee_member',
  'tenant',
  'housekeeping',
];

export const NAV_ITEMS = [
  { name: 'Dashboard', path: '/app', icon: LayoutDashboard, roles: ALL_ROLES },

  // Owner/tenant self-service
  { name: 'My Dues', path: '/app/my-dues', icon: Receipt, roles: ['resident', 'tenant'] },
  { name: 'List Property for Sale', path: '/app/list-property', icon: Tag, roles: ['resident', 'tenant'] },
  { name: 'Pets', path: '/app/pets', icon: PawPrint, roles: ALL_ROLES.filter((r) => !['housekeeping', 'accountant', 'treasurer'].includes(r)) },

  { name: 'Personal Data', path: '/app/flat-owners', icon: CreditCard, roles: ['secretary', 'chairman', 'resident', 'tenant'] },
  { name: 'Family Data', path: '/app/family-members', icon: Users2, roles: ['secretary', 'chairman', 'resident', 'tenant'] },
  { name: 'Vehicle Data', path: '/app/vehicles', icon: Car, roles: ['secretary', 'chairman', 'resident', 'tenant'] },
  { name: 'Home Services', path: '/app/home-services', icon: HomeIcon, roles: ['secretary', 'chairman', 'resident', 'tenant'] },
  { name: 'Role Checklist', path: '/app/role-checklist', icon: ClipboardCheck, roles: ALL_ROLES },
  { name: 'Society Rules', path: '/app/rules', icon: Gavel, roles: ALL_ROLES },
  { name: 'Service Providers', path: '/app/service-providers', icon: Wrench, roles: ALL_ROLES },
  { name: 'Parking', path: '/app/parking', icon: SquareParking, roles: ALL_ROLES },
  { name: 'Meeting Attendance', path: '/app/meeting-attendance', icon: UserCheck2, roles: ALL_ROLES.filter((r) => r !== 'housekeeping') },
  { name: 'Agenda Items', path: '/app/agenda-items', icon: ListChecks, roles: ALL_ROLES.filter((r) => r !== 'housekeeping') },
  { name: 'Elections', path: '/app/elections', icon: Vote, roles: ['secretary', 'chairman', 'treasurer', 'committee_member', 'resident', 'tenant'] },

  { name: 'Residents', path: '/app/residents', icon: Users, roles: ['security', 'secretary', 'chairman', 'treasurer', 'committee_member'] },
  { name: 'Gate Passes', path: '/app/gate-passes', icon: KeyRound, roles: ['security', 'secretary', 'chairman', 'resident', 'tenant'] },
  { name: 'Staff Shifts', path: '/app/shifts', icon: Clock4, roles: ['security', 'secretary', 'chairman', 'housekeeping'] },
  { name: 'Daily Tasks', path: '/app/tasks', icon: ClipboardList, roles: ['secretary', 'chairman', 'housekeeping'] },
  { name: 'Supplies', path: '/app/supplies', icon: Boxes, roles: ['secretary', 'chairman', 'housekeeping'] },
  { name: 'Lease Management', path: '/app/leases', icon: FileSignature, roles: ['secretary', 'chairman', 'committee_member', 'tenant'] },
  { name: 'Units / Flats', path: '/app/units', icon: Building2, roles: ['secretary', 'chairman'] },
  { name: 'Finance', path: '/app/finance', icon: Wallet, roles: ['accountant', 'secretary', 'chairman', 'treasurer', 'committee_member'] },
  { name: 'Visitors', path: '/app/visitors', icon: UserCheck, roles: ['security', 'secretary', 'chairman', 'tenant'] },
  { name: 'Complaints', path: '/app/complaints', icon: MessageSquareWarning, roles: ALL_ROLES },
  { name: 'Maintenance', path: '/app/maintenance', icon: Wrench, roles: ALL_ROLES },
  { name: 'Notice Board', path: '/app/notices', icon: Megaphone, roles: ALL_ROLES },
  { name: 'Amenities', path: '/app/amenities', icon: Dumbbell, roles: ALL_ROLES },
  { name: 'Documents', path: '/app/documents', icon: FileText, roles: ['secretary', 'chairman', 'accountant', 'treasurer', 'committee_member'] },
  { name: 'Meetings', path: '/app/meetings', icon: CalendarDays, roles: ALL_ROLES.filter((r) => r !== 'housekeeping') },
  { name: 'Voting / Polls', path: '/app/voting', icon: Vote, roles: ALL_ROLES.filter((r) => r !== 'housekeeping' && r !== 'security') },
  { name: 'Emergency (SOS)', path: '/app/emergency', icon: ShieldAlert, roles: ALL_ROLES },
  { name: 'Camera Requests', path: '/app/camera-requests', icon: Video, roles: ['security', 'secretary', 'chairman', 'resident', 'treasurer', 'committee_member', 'tenant'] },
  { name: 'Society Policies', path: '/app/policies', icon: ScrollText, roles: ALL_ROLES },
  { name: 'Investments & Assets', path: '/app/investments', icon: TrendingUp, roles: ['accountant', 'secretary', 'chairman', 'treasurer', 'committee_member'] },
  { name: 'Funds', path: '/app/funds', icon: PiggyBank, roles: ALL_ROLES.filter((r) => r !== 'housekeeping') },
  { name: 'Reports', path: '/app/reports', icon: BarChart3, roles: ['accountant', 'secretary', 'chairman', 'treasurer'] },
  { name: 'Society Structure', path: '/app/society-structure', icon: Building2, roles: ['chairman', 'secretary'] },
  { name: 'Settings', path: '/app/settings', icon: Settings, roles: ['secretary', 'chairman'] },
];
